# Generated by Django 3.2 on 2022-10-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=30, unique=True)),
                ('credit', models.CharField(max_length=5)),
                ('current_timestamp', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
        ),
    ]
