# Generated by Django 3.2 on 2022-11-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0002_auto_20221011_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hours',
            field=models.CharField(default=0, max_length=5),
        ),
    ]
